version: '3.1'

services:
  grafana:
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana:/etc/grafana
      - ./dashboards:/app/dashboards
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
